### ISSUE TITLE
[Android] Maptiler test case json files strange content

### ISSUE THREAD

**Issue by JtxGit** [mousebird-consulting-inc/WhirlyGlobe#1380]
While trying the Android test cases, I ran across this.

The json files do not seem to have real content, but seems to be pointers to some other location that is not accessible. For example:

WhirlyGlobe/android/apps/AutoTesterAndroid/app/src/main/assets/maptiler_basic.json 
has this content:
"../../../../../../../resources/vectors/styles/maptiler_basic.json"

These files are affected:

        "maptiler_basic.json",
        "maptiler_streets.json",
        "maptiler_topo.json",
        "maptiler_hybrid_satellite.json",
        "maptiler_expr_test.json",

**Comment by mousebird** [comment]
Is that in the submodule?
Do a git submodule init and look in the resources folder.

**Comment by JtxGit** [comment]
I downloaded the source as the zip under Releases:
https://github.com/mousebird-consulting-inc/WhirlyGlobe/archive/refs/tags/v3.2.zip

In this zip, the correct content of the json files do not exist.

**Comment by mousebird** [comment]
You need that submodule.  Not sure what to suggest if you downloaded the source.

**Comment by TimSylvester-mousebird** [comment]
@JtxGit If you're downloading the source archive for the main repo, you'll need to also download the corresponding archive for the resources module and unpack it in the right location, a `resources` directory at the root.  I created a matching tag on the resources submodule at the equivalent commit to make this easier.

https://github.com/mousebird/wg-resources-new/releases/tag/v3.2

I'm going to close this because we will not be including the resources in the main repository, which is the only way that they would appear in GitHub's automatic archives of the repo.

@mousebird We can create releases with attached files from a tag, so we could attach the resources archive to the main repo's release to make this more straightforward for people not using git.
