### ISSUE TITLE
How to move vector map texts layer to back?

### ISSUE THREAD

**Issue by akovalov** [mousebird-consulting-inc/WhirlyGlobe#1511]
We use an OSM vector map as `mbtiles` file and `MapboxVectorStyleSet`to parse mapbox like style. 
We have `MaplyScreenMarker` objects on the map with `layoutSize = .zero` (to allow overlap with other markers).
And when the map texts (countries and cities names) overlap with these markers - markers disappear.
The `MaplyBaseViewController` has `maplyVC.screenObjectDrawPriorityOffset = 0`.

How we can set map texts layer to have less priority or to show below markers?

**Comment by mousebird** [comment]
@TimSylvester-mousebird can you answer this one?

**Comment by TimSylvester-mousebird** [comment]
Not sure I understand the question; there's layout, which it sounds like is hiding the markers, and then there's draw priority, which affects ordering.

It sounds like you're talking about objects added from a stylesheet layer as well as ones you're adding directly (with a specific layout size)?

For stylesheets, you can avoid layout conflicts with the `[icon|text]-allow-overlap` options.  I'm not sure what is the expected behavior of a zero layout size, but using `layoutImportance=MAXFLOAT` disables layout entirely, so I'd say it should do something different, like placing it if possible, but not blocking anything else from being placed.

The draw priority of style layers is set from the order in which the layers are defined, with a fixed base of 1,000,000 for symbols.  So to add markers that are always above style layers, you'd want to add to that at least the number of layers multiplied by the style settings `drawPriorityPerLevel` value.

It would probably be a good idea to move that fixed base and other hard-coded values to the style settings so that they can be adjusted dynamically.

**Comment by akovalov** [comment]
@TimSylvester-mousebird thank you very much for the detailed reply. 
Yes, the texts (countries and cities names) from the OSM file cause screen markers to disappear when overlap with them.
Fixed it by adding `"text-allow-overlap": true` to the stylesheet for the countries and cities names layers.
